// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeQlQ3veLAdSSdDHhxbNOfucfGC63XpM',
    appId: '1:793366152220:web:0f7282819c924abbf04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    authDomain: 'blog-app-3-p.firebaseapp.com',
    storageBucket: 'blog-app-3-p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FCCcqpkUm_REPyDTns4zCyxi0Ey9QI8',
    appId: '1:793366152220:android:3f6bbaf63df878b7f04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    storageBucket: 'blog-app-3-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Jc0vX0dt2OJxrgvN8-BfiHQeJq7Fe_o',
    appId: '1:793366152220:ios:0d2f13d1644776bbf04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    storageBucket: 'blog-app-3-p.appspot.com',
    iosClientId: '793366152220-mk8m6i9hqc1l25snqd3l6rbat6nvace0.apps.googleusercontent.com',
    iosBundleId: 'none',
  );
}
